from typing import Any, Protocol

from app.billing.models import BillingPlan


class PaymentProvider(Protocol):
    async def initialize_subscription_checkout(self, email: str, plan: BillingPlan, user_id: str) -> dict[str, Any]: ...

    async def get_subscription(self, subscription_code: str) -> dict[str, Any]: ...

    async def cancel_subscription(self, subscription_code: str, email: str) -> bool: ...

    async def enable_subscription(self, subscription_code: str, email: str) -> bool: ...

    async def fetch_customer(self, email: str) -> dict[str, Any] | None: ...
