"""Data schemas and transfer objects for the Smart Model Router."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field

from app.models.attachments import AttachmentType
from app.models.config import ModelProvider, RoutingMode, TextModelConfig


class TaskType(str, Enum):
    """Categorized task taxonomy for incoming user requests."""

    CODING = "coding"
    GENERAL_KNOWLEDGE = "general_knowledge"
    CREATIVE_WRITING = "creative_writing"
    ANALYSIS = "analysis"
    SUMMARIZATION = "summarization"
    MATH_REASONING = "math_reasoning"
    CONVERSATION = "conversation"
    OTHER = "other"


class CapacityStatus(str, Enum):
    """Model capacity status relative to request complexity."""

    SUFFICIENT_CAPACITY = "sufficient_capacity"
    CAPACITY_DEFICIT = "capacity_deficit"


class ScoreDimension(str, Enum):
    """Evaluation scoring dimensions."""

    CAPABILITY = "capability"
    COMPLEXITY = "complexity"
    QUALITY = "quality"
    SPEED = "speed"
    COST = "cost"
    RELIABILITY = "reliability"


class RequestAnalysis(BaseModel):
    """Structured request analysis generated by Gemini Flash-Lite or heuristic analyzer."""

    task_type: TaskType = Field(
        default=TaskType.GENERAL_KNOWLEDGE,
        description="Categorized primary task type (e.g. coding, general_knowledge, analysis, creative_writing, math_reasoning, summarization, conversation)",
    )
    complexity: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Estimated overall complexity on a 0.0 - 1.0 scale (0.2: simple query, 0.5: moderate, 0.8: hard, 0.95: deeply complex reasoning).",
    )
    reasoning_required: float = Field(
        default=0.3,
        ge=0.0,
        le=1.0,
        description="Estimated need for deep multi-step logical reasoning (0.0: none, 1.0: maximum).",
    )
    context_required: float = Field(
        default=0.2,
        ge=0.0,
        le=1.0,
        description="Estimated reliance on long conversation history or large documents (0.0: none, 1.0: massive context needed).",
    )
    coding_required: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Estimated degree of software engineering, code generation, refactoring, or debugging needed.",
    )
    creative_required: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Estimated degree of open-ended creative writing or stylistic generation needed.",
    )
    vision_required: bool = Field(
        default=False,
        description="True if image/visual perception or analysis is required.",
    )
    web_required: bool = Field(
        default=False,
        description="True if recent real-time web search/grounding is required.",
    )
    tool_calling_required: bool = Field(
        default=False,
        description="True if tool/function calling is required.",
    )
    structured_output_required: bool = Field(
        default=False,
        description="True if strict schema/JSON structured output is required.",
    )
    estimated_output_tokens: int | None = Field(
        default=None,
        ge=1,
        description="Optional estimated token count for the response.",
    )
    confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Analyzer confidence score in this classification.",
    )


class RequestContext(BaseModel):
    """Contextual metadata passed alongside the user message to aid routing."""

    conversation_message_count: int = Field(default=0, ge=0)
    approximate_context_tokens: int = Field(default=0, ge=0)
    has_attachments: bool = False
    attachment_types: list[AttachmentType] = Field(default_factory=list)
    recent_message_summary: str | None = None
    user_id: str | None = None
    session_id: str | None = None


class PolicyWeights(BaseModel):
    """Weights applied by a routing policy during model scoring (must sum to ~1.0)."""

    capability_weight: float = Field(default=0.25, ge=0.0, le=1.0)
    complexity_weight: float = Field(default=0.25, ge=0.0, le=1.0)
    quality_weight: float = Field(default=0.20, ge=0.0, le=1.0)
    speed_weight: float = Field(default=0.15, ge=0.0, le=1.0)
    cost_weight: float = Field(default=0.15, ge=0.0, le=1.0)
    reliability_weight: float = Field(default=0.00, ge=0.0, le=1.0)


class RoutingPolicy(BaseModel):
    """Configuration governing model filtering and scoring trade-offs."""

    mode: RoutingMode = RoutingMode.BALANCED
    weights: PolicyWeights = Field(default_factory=PolicyWeights)
    max_cost: float | None = None
    allowed_models: list[str] | None = None
    preferred_providers: list[ModelProvider] | None = None
    min_capability_threshold: float = 0.0
    fallback_model: str | None = None


class ScoreBreakdown(BaseModel):
    """Detailed score breakdown for transparent and explainable model selection."""

    capability_match: float
    complexity_match: float
    quality_score: float
    speed_score: float
    cost_score: float
    reliability_score: float
    raw_scores: dict[str, float] = Field(default_factory=dict)
    weighted_scores: dict[str, float] = Field(default_factory=dict)
    details: dict[str, Any] = Field(default_factory=dict)


class ScoredCandidate(BaseModel):
    """An eligible candidate model evaluated by the deterministic scoring engine."""

    model_config = ConfigDict(populate_by_name=True)

    model_id: str
    provider: ModelProvider
    total_score: float
    rank: int
    breakdown: ScoreBreakdown
    model_config_data: TextModelConfig = Field(..., alias="model_config")


class RoutingDecision(BaseModel):
    """Final output produced by the Smart Model Router."""

    selected_model_id: str
    provider: ModelProvider
    score: float
    routing_mode: RoutingMode
    task_type: TaskType
    complexity: float
    reason: ScoreBreakdown
    ranked_candidates: list[ScoredCandidate] = Field(default_factory=list)
    analysis: RequestAnalysis
    fallback_models: list[str] = Field(default_factory=list)
    is_fallback_decision: bool = False
    metadata: dict[str, Any] = Field(default_factory=dict)


class RoutingTelemetry(BaseModel):
    """Internal telemetry event generated on every routing decision."""

    request_id: str = Field(default_factory=lambda: f"route_{uuid4().hex[:12]}")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    selected_model: str
    provider: ModelProvider
    routing_mode: RoutingMode
    task_type: TaskType
    complexity: float
    score: float
    candidate_models: list[str] = Field(default_factory=list)
    filtered_out_models: dict[str, str] = Field(default_factory=dict)
    analysis_latency_ms: float | None = None
    scoring_latency_ms: float | None = None
    total_latency_ms: float | None = None
    is_fallback: bool = False
